# Site
repository: hansolyoon/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Hansol Yoon
title: PhD student, University of Colorado Boulder
email: hansol.yoon at colorado dot edu
# website: www.github.com/sproogen/resume-theme

# Social links
# twitter_username: facespics
github_username: hansolyoon
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: hansol-yoon-a5a372b7
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am Hansol Yoon, a PhD student in Professor Sriram Sankaranarayanan's group and the Computer Science department at the University of Colorado Boulder.

  I got my Masters degree from the University of Colorado Boulder in 2019 and received my Bachelors degree from Korea Air Force Academy in 2010.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: Publications
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: hansolyoon/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
